#!/usr/bin/env node

// Git extension wrapper for create-pr
// This allows using 'git create-pr' instead of just 'create-pr'

const { spawn } = require('child_process');
const path = require('path');

// Get the directory where this script is located
const scriptDir = __dirname;
const createPrScript = path.join(scriptDir, 'bin', 'create-pr');

// Forward all arguments to the original create-pr script
const args = process.argv.slice(2);

// Spawn the create-pr command with all arguments
const child = spawn('node', [createPrScript, ...args], {
  stdio: 'inherit',
  shell: true
});

// Handle process events
child.on('close', (code) => {
  process.exit(code || 0);
});

child.on('error', (error) => {
  console.error('Error running create-pr:', error.message);
  process.exit(1);
});